### ISSUE TITLE
Не работает Docker

### ISSUE THREAD

**Issue by YuliyaGer** [YuliyaGer/Diplom#1]
Окружение: Windows 7. Не могу запустить Docker.
1. Cкачан и установлен DockerToolbox-19.03.1:
![image](https://user-images.githubusercontent.com/56927385/73088561-8f402500-3ee5-11ea-9bf7-2d50e54fdbde.png)

2. При запуске Docker Quickstart Terminal:
![image](https://user-images.githubusercontent.com/56927385/73088885-30c77680-3ee6-11ea-9323-c8c63afbef76.png)

3. При попытке запустить контейнеры в Idea:
![image](https://user-images.githubusercontent.com/56927385/73088954-5785ad00-3ee6-11ea-8494-f27eecd4d8ec.png)

**Comment by coursar** [comment]
Скриншоты очень плохого качества. Что конкретно написано в Docker Quick Start Terminal? Сколько ждали после старта?
